### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by rudradave1** [rudradave1/TriviaApp#4]
This project needs a good readme file complementing the project.

**Comment by nilis24** [comment]
Hello, I would like to work on this issue. Can you assign it to me please?

**Comment by rudradave1** [comment]
Sure, @nilis24 go ahead.

**Comment by divyansh-dxn** [comment]
Hey! are the issues still up for Hacktoberfest 2022?

**Comment by rudradave1** [comment]
> Hey! are the issues still up for Hacktoberfest 2022?

No this is not for Hacktoberfest this year.
